/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./screens/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#03224d',
        'on-primary': '#ffffff',
        'primary-container': '#1f3864',
        'on-primary-container': '#8ba2d5',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#afc6fb',
        secondary: '#835400',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb64e',
        'on-secondary-container': '#714800',
        'secondary-fixed': '#ffddb5',
        'secondary-fixed-dim': '#ffb956',
        background: '#f7f9fc',
        'on-background': '#191c1e',
        surface: '#f7f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#44474f',
        outline: '#747780',
        'outline-variant': '#c4c6d0',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        tertiary: '#00224d',
        success: '#4CAF50',
        warning: '#FF9800',
        danger: '#F44336',
        gold: '#feb64e',
        dark: '#0A0A0A',
        card: '#ffffff',
      },
    },
  },
  plugins: [],
}
